---
# vars file for vsftpd_installation

# vars for vsftpd.conf
anonymous_enable: YES
local_enable: NO
write_enable: YES
anon_upload_enable: YES
anon_root: /var/ftp
vsftpd_config: /etc/vsftpd/vsftpd.conf
upload_dir: /var/ftp/pub/upload

# vars for confifre selinux
context: public_content_rw_t

