---
- name: Httpd intall playbook
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: False

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Enable & start httpd
    systemd:
      name: httpd
      enabled: yes
      state: started
  - name: Copy index.html
    copy: src=files/index.html dest=/var/www/html/index.html mode=0664
  - name: Enable & start firewalld
    systemd:
      name: firewalld
      enabled: yes
      state: started
  - name: Permit http
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify: Firewald reload
  handlers: 
  - name: Firewald reload
    systemd:
      name: firewalld
      state: reloaded
