---
- name: Httpd remove playbook
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: False

  tasks:
  - name: Reset net.ifnames=1, biosdevname=1 parameters to =0
    lineinfile:
      path: /etc/default/grub
      state: present
      backrefs: yes
      regexp:  '^(GRUB_CMDLINE_LINUX=\".*){{ item }}=1(.*\")'
      line: '\1{{ item }}=0\2'
      backup: yes
    notify: run grub2-mkconfig
    loop:
      - net.ifnames
      - biosdevname
  - name: Add net.ifnames=0, biosdevname=0 parametrs
    lineinfile:
      path: /etc/default/grub
      state: present
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*{{ item }}.*)\".+)(\")'
      line: '\1 {{ item }}=0\2'
      backup: yes
    notify: run grub2-mkconfig
    loop:
      - audit
      - net.ifnames
  handlers:
  - name: run grub2-mkconfig
    command: grub2-mkconfig
