---
# tasks file for httpd_installation
- name: Include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"
- name: Install httpd
  yum:
    name: httpd
    state: present
- name: Enable http
  systemd:
    name: httpd
    enabled: yes
- name: Make sure a service unit httpd is running
  systemd:
    state: started
    name: httpd
- name: Copy index.html
  template:
    src: index.html.j2
    #dest: /var/www/html/index.html 
    dest: "{{ index_html_path }}"
    mode: 0664  
- name: Enable firewalld
  systemd:
    name: firewalld
    enabled: yes
- name: permit http
  firewalld:
    service: http
    permanent: true
    state: enabled    
  notify: Firewald reload
