---
# tasks file for httpd_installation
- name: Include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"
- name: Install httpd
  yum:
    name: httpd
    state: present
- name: Enable & start http
  systemd:
    name: httpd
    enabled: yes
    state: started
- name: Copy index.html
  template:
    src: index.html.j2
    dest: "{{ index_html_path }}"
    mode: 0664  
- name: Enable & start firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started
- name: permit http
  firewalld:
    service: http
    permanent: true
    state: enabled    
  notify: Firewald reload
